kind: Deployment
apiVersion: apps/v1
metaadta:
  name: app1
  labels:
    app: nginx
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: web
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
        - name: app1
          image: kavya478/app1:1.0.0 
          ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector:
    app: nginx
    tier: web
  ports:
  - protocol:
    ports: 80
    targetPort: 80
    nodePort: 30007

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listener-ports: '[{ "HTTPS": 443 }]'
    alb.ingress.kubernetes.io/certficate-arn:
    alb.ingress.kubernetes.io/group-name: kavya478
spec:
  ingressClassName: alb
  rules:
  - host: kavyadev.shop
    http:
      paths:
      - pathType: 
        path: "/"
        backend: 
          service:
            name: app1
            ports:
              number: 80